// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfprublxsrxalzkxykqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmcHJ1Ymx4c3J4YWx6a3h5a3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzk0MDgsImV4cCI6MjA2NjYxNTQwOH0.HpAxt1Y5ArHtZZQg41wWO8b_D2eLp4ql_gkiRmP7Bh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);